import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * Next's recommended rules plus TypeScript. Kept deliberately close to the
 * defaults — a bespoke rule set is one more thing to maintain for a codebase
 * this size.
 */
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and uses triple-slash references.
    ignores: [
      ".next/**",
      "node_modules/**",
      ".data/**",
      "screenshots/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts",
      // Vendored MediaPipe runtime — a generated Emscripten bundle, not ours to
      // lint or to fix.
      "public/vision/**",
      "style-previews/**",
      "viewport-*/**",
    ],
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
    },
  },
];

export default config;
